language: node_js

services:
  - docker

before_install: 
  - docker build -t udagram-api-feed ./projects/udagram-api-feed
  - docker tag udagram-api-feed destinyajax/udagram-api-feed:v1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push destinyajax/udagram-api-feed:v1